(err, res) => {
    // process the error and result
}